### ISSUE TITLE
Epic: Upgrade tkn-results to work with v0.5.0

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#391]
### Feature request

Upgrade `tkn-results` CLI plugin so that it works with the latest set of features in Tekton Results.

This could potentially be a large "epic" with multiple sub-issues:

- [x] ~~Use REST instead of gRPC~~ _Not required, gRPC and REST use the same port_.
- [ ] Add sub-command for logs (list, get)
- [ ] Use `kubeconfig` for authentication

### Use case

- Access Results data using a CLI tool.
- Retrieve archived logs from Tekton via CLI.

**Comment by khrm** [comment]
We were planning on making it work and then donating to tekton/cli project.

**Comment by avinal** [comment]
Hey @khrm, I have been working on it for a while. If you would also like to work on it, we can split the tasks.

**Comment by khrm** [comment]
Sure. What are you tackling from this task?
